### ISSUE TITLE
sewing-kit.config.ts generated file is incompatible with default project 

### ISSUE THREAD

**Issue by ewalk153** [Shopify/quilt#1033]
## Overview

When running `rails g sewing_kit:install`, the config file does export the module properly. The following error message is generated:
```
[error] Type errors encountered while parsing sewing-kit config:
    /Users/ericwalker/src/github.com/Shopify/quilt-rails-example/config/sewing-kit.config.ts (3,1): All files must be modules when the '--isolatedModules' flag is provided.
Error: Type errors encountered while parsing sewing-kit config:
    /Users/ericwalker/src/github.com/Shopify/quilt-rails-example/config/sewing-kit.config.ts (3,1): All files must be modules when the '--isolatedModules' flag is provided.
    at /Users/ericwalker/src/github.com/Shopify/quilt-rails-example/node_modules/@shopify/sewing-kit/dist/src/workspace/config.js:123:19
    at Generator.next (<anonymous>)
    at fulfilled (/Users/ericwalker/src/github.com/Shopify/quilt-rails-example/node_modules/@shopify/sewing-kit/dist/src/workspace/config.js:4:58)
```

The fix is to export with: `export default sewingKitConfig;`

**Comment by GoodForOneFare** [comment]
Thanks for letting us know!  Fixed by #1033, releasing in `quilt_rails@1.8.0`.
