### ISSUE TITLE
@shopify/koa-shopify-auth package not installable

### ISSUE THREAD

**Issue by brettbullock** [Shopify/quilt#1389]
## Overview
When trying to install `@shopify/koa--shopify-auth` using the instructions provided on the npm documentation (https://www.npmjs.com/package/@shopify/koa-shopify-auth), the command does not execute as expected, fails, and returns an error.

### Steps to reproduce:
1. Run `$ yarn add @shopify/koa-shopify-auth` in terminal

### Expected behaviour
Package is installed successfully after running install command.

### Actual behaviour
Package install fails with the following error: 
`error Couldn't find package "@shopify/koa-shopify-auth" on the "npm" registry.`

When running `$ yarn add @shopify/koa-shopify-auth --verbose`, the following is logged:
```
yarn add v1.19.1
verbose 0.158096709 Checking for configuration file "/Users/brettbullock/code/shopify-auction-app/.npmrc".
verbose 0.158339494 Checking for configuration file "/Users/brettbullock/.npmrc".
verbose 0.158487988 Found configuration file "/Users/brettbullock/.npmrc".
verbose 0.158771401 Checking for configuration file "/usr/local/etc/npmrc".
verbose 0.158934722 Checking for configuration file "/Users/brettbullock/code/shopify-auction-app/.npmrc".
verbose 0.15908489 Checking for configuration file "/Users/brettbullock/code/.npmrc".
verbose 0.159243818 Checking for configuration file "/Users/brettbullock/.npmrc".
verbose 0.159394558 Found configuration file "/Users/brettbullock/.npmrc".
verbose 0.15961276 Checking for configuration file "/Users/.npmrc".
verbose 0.161047728 Checking for configuration file "/Users/brettbullock/code/shopify-auction-app/.yarnrc".
verbose 0.161202779 Checking for configuration file "/Users/brettbullock/.yarnrc".
verbose 0.161327189 Found configuration file "/Users/brettbullock/.yarnrc".
verbose 0.161549639 Checking for configuration file "/usr/local/etc/yarnrc".
verbose 0.161696844 Checking for configuration file "/Users/brettbullock/code/shopify-auction-app/.yarnrc".
verbose 0.161822122 Checking for configuration file "/Users/brettbullock/code/.yarnrc".
verbose 0.161934739 Checking for configuration file "/Users/brettbullock/.yarnrc".
verbose 0.162019869 Found configuration file "/Users/brettbullock/.yarnrc".
verbose 0.16221592 Checking for configuration file "/Users/.yarnrc".
verbose 0.164850806 current time: 2020-04-20T12:58:17.094Z
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] 🔍  Resolving packages...
verbose 0.341999157 Performing "GET" request to "https://packages.shopify.io/shopify/node/npm/@shopify%2fkoa-shopify-auth".
verbose 0.771748716 Request "https://packages.shopify.io/shopify/node/npm/@shopify%2fkoa-shopify-auth" finished with status code 401.
verbose 0.785525369 Error: Couldn't find package "@shopify/koa-shopify-auth" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.19.1/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.19.1/libexec/lib/cli.js:750:123)
    at NpmResolver.<anonymous> (/usr/local/Cellar/yarn/1.19.1/libexec/lib/cli.js:50683:15)
    at Generator.next (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.19.1/libexec/lib/cli.js:304:30)
    at /usr/local/Cellar/yarn/1.19.1/libexec/lib/cli.js:315:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
error Couldn't find package "@shopify/koa-shopify-auth" on the "npm" registry.
```

It seems as though authorization is required to fetch the package. I tried to visit the package download URL in my browser (`https://packages.shopify.io/shopify/node/npm/@shopify%2fkoa-shopify-auth` ) and the following was returned on the browser:
`Incorrect username or API token`

### Additional Troubleshooting Actions Taken
I've tried a couple ways to resolve the issue here. 
1. removed yarn from the project and re-added
2. cleaned yarn cache `yarn cache clean`
3. tried using `npm install @shopify/koa-shopify-auth`
4. tried setting my yarn registry to npm's registry `yarn config set registry https://registry.npmjs.org/`

**Comment by NBowes** [comment]
I'm getting this error as well. What I'm running:

`npm i --save @shopify/koa-shopify-auth`

And this is the logs I see:

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'i',
1 verbose cli   '--save',
1 verbose cli   '@shopify/koa-shopify-auth'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v12.14.1
4 verbose npm-session 12581b781876de0c
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 401 https://packages.shopify.io/shopify/node/npm/@shopify%2fkoa-shopify-auth 440ms
8 silly fetchPackageMetaData error for @shopify/koa-shopify-auth@latest 401 Unauthorized - GET https://packages.shopify.io/shopify/node/npm/@shopify%2fkoa-shopify-auth
9 timing stage:rollbackFailedOptional Completed in 0ms
10 timing stage:runTopLevelLifecycles Completed in 1047ms
11 verbose stack Error: 401 Unauthorized - GET https://packages.shopify.io/shopify/node/npm/@shopify%2fkoa-shopify-auth
11 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:104:15
11 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:94:5)
12 verbose statusCode 401
13 verbose pkgid @shopify/koa-shopify-auth@latest
14 verbose cwd /Users/nathenbowes/code/shopify-react-next
15 verbose Darwin 18.7.0
16 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "--save" "@shopify/koa-shopify-auth"
17 verbose node v12.14.1
18 verbose npm  v6.13.4
19 error code E401
20 error 401 Unauthorized - GET https://packages.shopify.io/shopify/node/npm/@shopify%2fkoa-shopify-auth
21 verbose exit [ 1, true ]
```

I was also taking a look through StackOverflow and was able to list my NPM config and found my .npmrc file. It has an authToken in it - I didn't want to post it here, but here is what it looks like:

```
@shopify:registry=https://packages.shopify.io/shopify/node/npm/
//packages.shopify.io/shopify/node/npm/:_authToken=SECRET_AUTH_TOKEN
registry=https://registry.npmjs.org
```
I also noticed that `/node/npm/` isn't a folder/repo listed on packages.shopify.com/shopify, so I'm wondering if the authentication has changed, or just the place for that package. 

![](https://screenshot.click/20-40-2vh3j-z6l9i.png)

Any insight into this would be awesome :)

**Comment by michenly** [comment]
This is a problem due to internal private registry, try setting the registry on your local to the public one instead, install and switch back to private after.

**Comment by ashleyfulks** [comment]
Thanks to Nathen for the fix. You can try

> rm ~/.npmrc

Which should remove the offending NPM profile.
