### ISSUE TITLE
Updates to `react-dom` 17 are not working

### ISSUE THREAD

**Issue by arthurgouveia** [Shopify/quilt#1686]
## Overview

We've just gotten a [dependabot PR](https://github.com/Shopify/email/pull/6804) to bump `react-dom` to `17.0.1` and CI is failing with reports on the `react-testing` such as

`Attempted to operate on a mounted tree, but the component is no longer mounted`
...
`at destroyAll (node_modules/@shopify/react-testing/dist/src/destroy.js:10:21)`

and 

`TypeError: Cannot read property 'alternate' of undefined`
...
`at mount (node_modules/@shopify/react-testing/dist/src/mount.js:9:12)`

These can be seen on the build link on the mentioned PR above.

## Consuming repo

https://github.com/Shopify/email

**Comment by BPScott** [comment]
Probably worth working this out as part of React v17 plans.
