### ISSUE TITLE
[react-form] Application fails to build when using react-form package

### ISSUE THREAD

**Issue by ryanwilsonperkin** [Shopify/quilt#1715]
## Overview

Service fails to build after installing and using `@shopify/react-form`. The error message is as follows:

```
[client (latest)] Compile failed with errors
Error: webpack has removed these modules:
    "./node_modules/@shopify/react-form/index.esnext"

• If a module is necessary for production, preserve it by adding it to package.json#sideEffects (for more information, see https://github.com/webpack/webpack/tree/master/examples/side-effects)
• If a module can be safely removed, add it to FailOnUnexpectedModuleShakingPlugin's 'exclude' list
    at /Users/ryan/src/github.com/Shopify/react-form-error-example/node_modules/@shopify/sewing-kit/dist/src/tools/webpack/index.js:116:23
    at Generator.next (<anonymous>)
    at fulfilled (/Users/ryan/src/github.com/Shopify/react-form-error-example/node_modules/@shopify/sewing-kit/dist/src/tools/webpack/index.js:24:58)
```

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/3004111/102932820-058b3580-446f-11eb-855e-17b0deaf3f38.png)

</details>

This unfortunately means that the package can't be used at the moment, without extra configuration to the service's webpack configuration.

### Steps to reproduce

1. Clone [this repo](https://github.com/Shopify/react-form-error-example/) with `dev clone react-form-error-example`
2. `dev up`
3. `yarn sewing-kit build`

You should expect to see the same compile error message. This reproduction example is the baseline React/Rails app generated with `dev init` and then modified in a [single commit](https://github.com/Shopify/react-form-error-example/commit/009b3f02a46823c8c3c1ab3708949d160f817712) to install the `@shopify/react-form` package and to use the [example code provided in the README](https://www.npmjs.com/package/@shopify/react-form).

## Consuming repo

I originally encountered this in https://github.com/shopify/services-db however I have setup a minimal reproducing case at https://github.com/Shopify/react-form-error-example/ , specifically in [this commit](https://github.com/Shopify/react-form-error-example/commit/009b3f02a46823c8c3c1ab3708949d160f817712)

**Comment by ryanwilsonperkin** [comment]
The error message states that this can be avoided by adding the reference to `FailOnUnexpectedModuleShakingPlugin`'s exclude list, but that value is [hardcoded by sewing-kit to an empty array](https://github.com/Shopify/sewing-kit/blob/63f83a8b179d92a64d3f4c4e2128f081bb50c0ea/packages/sewing-kit/src/tools/webpack/config/plugins.ts#L176-L178).

For now, I'll try to work around this by declaring the file to have side effects.

**Comment by ryanwilsonperkin** [comment]
Adding the file to the list of sideEffects also does not have the desired effect, I'll try downgrading to v0.10

**Comment by ismail-syed** [comment]
Thanks for filing this issue. Before merging https://github.com/Shopify/quilt/pull/1698, I 🎩 'd various quilt packages in shrink-ray (https://github.com/Shopify/shrink-ray/pull/1718). Our sewing-kit tooling does consume `esnext` builds in packages as expected. I'm not entirely sure what's up with react-form though. 

`FailOnUnexpectedModuleShakingPlugin's` takes and `exclude` option which you can configure in your projects sewing-kit config. Here's a [changeset](https://github.com/Shopify/shrink-ray/commit/0b439b9e466614294e826ea8a7b1e8fd1df1a8c6) which I used when testing in shrink-ray, I was able to fix it with that. That should work with services-db as well. 


Webpack tries to help improve performance by removing code it thinks it doesn't need. IIRC, in the past we've had prod issues were it has removed modules we actually needed. `FailOnUnexpectedModuleShakingPlugin's` was born out of these issues. I've seen some apps across the org leverage `FailOnUnexpectedModuleShakingPlugin.options.exclude` to exclude certain `@shopify/polaris` component bundle. We may have to do the same with `@react-form`. 

cc/ @TheMallen, anything come to mind in react-form that could be causing this? 

--- 

I also ran some shrink-ray tests with `@shopify/react-form@0.10.0` vs the latest release with esbuild support. The production builds are behaving as expected. 🤔 

## @shopify/react-form@0.10.0

The production build is consuming the entire react-form package yielding a ~6KB vendor bundle for the page I included react-form in. 

* [GitHub check](https://github.com/Shopify/shrink-ray/runs/1601412349)
* [Detailed shrink-ray report](https://shrink-ray-staging.shopifycloud.com/repos/shrink-ray/commits/9947bccc43d2edc29f3e77f10d6e99f51083aa71/net_diff?assetTypeFilter=unchanged)  

<img width="981" alt="Screen Shot 2020-12-23 at 1 15 43 PM" src="https://user-images.githubusercontent.com/6130700/103026059-12686180-4521-11eb-8bba-b945056e91fb.png">


## @shopify/react-form@0.11.0 (Latest)

When consuming the `esnext` build, webpack can treeshake the 3rd party module better, yeilding a ~3KB vendor bundle for that page. 

* [GitHub check](https://github.com/Shopify/shrink-ray/runs/1601445328)
* [Detailed shrink-ray report](https://shrink-ray-staging.shopifycloud.com/repos/shrink-ray/commits/0b439b9e466614294e826ea8a7b1e8fd1df1a8c6/net_diff?assetTypeFilter=unchanged)

<img width="913" alt="Screen Shot 2020-12-23 at 1 19 25 PM" src="https://user-images.githubusercontent.com/6130700/103026311-a0444c80-4521-11eb-8f04-d34596c661cc.png">

**Comment by ryanwilsonperkin** [comment]
Thanks for the detailed write-up @ismail-syed! For the moment, I've downgraded to v0.10 which successfully resolved the issue. Given the tradeoff between the additional package size versus the changeset to add `FailOnUnexpectedModuleShakingPlugin` we'd probably choose the former (our emphasis right now is more on code/config simplicity than bytes-over-the-wire).

Is there anything else I can help provide to dig into this further? It seems to me that perhaps `index.esnext` being dropped as a module is a reasonable expectation for this module since it is just re-exporting all values. Is Webpack perhaps smart enough to drop it and just resolve those re-exported values instead?

**Comment by GoodForOneFare** [comment]
The plugin is just plain wrong here, and it should be removed from sewing-kit.  It used to be useful for flagging global CSS imports being silently dropped from production bundles, but it's providing negative value now.

**Comment by DougEdey** [comment]
Same issue on SpyV2 with this change, I'm not tracking the conversation here, so I'm not sure if there is a fix yet.

**Comment by ismail-syed** [comment]
@DougEdey, you can apply this [changes](https://github.com/Shopify/shrink-ray/commit/0b439b9e466614294e826ea8a7b1e8fd1df1a8c6) to resolve the issue.

**Comment by ryanwilsonperkin** [comment]
Just ran into an issue with `react-network` as well when upgrading from `3.5.8` to `3.6.0`. It seems that the only material change between the two was the switch to the build system, but our app now fails when installing 3.6.0 (we [reverted](https://github.com/Shopify/services-db/pull/6720))

We began getting [this error](https://github.com/Shopify/quilt/blob/a7594add91ec3fc3ddc73ec12865ba71c3d863f6/packages/react-network/src/test/NetworkUniversalProvider.test.tsx#L112) in the console, despite setting up the `NetworkProvider` context provider

**Comment by ismail-syed** [comment]
@ryanwilsonperkin, @dirceu We were able to upgrade to `@shopify/react-network@3.6.0` without any issues. What you experienced with `react-network` is different from this issue description regarding `react-form`. 

I took a look at https://github.com/Shopify/services-db/pull/6702. If you look at the `yarn.lock`, that PR is introducing duplicate dependencies for some packages (eg. `@shopify/react-html`). I suspect that was the issue. Duplicate dependencies of various quilt packages will cause SSR issues because it leads to duplicate React contexts across libraries which get mucked up during an SSR. You can dedupe these packages running `npx yarn-deduplicate --scopes @shopify yarn.lock`. This could have also happened with [`react-i18n`](https://github.com/Shopify/quilt/tree/master/packages/react-i18n-universal-provider#possible-issues).

**Comment by ryanwilsonperkin** [comment]
Thanks @ismail-syed ! Will try that dep upgrade again now

**Comment by DougEdey** [comment]
Thanks @ismail-syed fixed with [`8c6539f` (#655)](https://github.com/Shopify/spy-v2/pull/655/commits/8c6539f337006cebc73f705bf5fca4e1429eb6df)

**Comment by ryanwilsonperkin** [comment]
We've done a similar fix now in https://github.com/Shopify/services-db/pull/6697 to allow us to get to the latest version of `react-form` and `react-graphql`. I'd like to keep this issue open though if that's alright with those involved because I think a full resolution for this would probably require one of the following:
1. Change to the bundling format of Quilt packages to fix these index files (if there's an issue with them)
2. Change to sewing-kit's webpack config to prevent this plugin from flagging index files (if there isn't an issue with them)
3. Change to the sewing-kit/quilt generator so that new apps automatically get these overrides in `sewing-kit.config.ts`

Sound good?

**Comment by Mangara** [comment]
Is there any update on a fix for this?
