### ISSUE TITLE
[graphql-mini-transforms] Unable to import fragment file in javascript

### ISSUE THREAD

**Issue by pleunv** [Shopify/quilt#1776]
Hi guys! I'm looking into `graphql-mini-transforms` as possible replacement for `graph-tag/loader`, but ran into one annoying issue. We have some instances where we use apollo's [writeFragment/readFragment](https://www.apollographql.com/docs/react/caching/cache-interaction/#writequery-and-writefragment) to do optimistic store updates. In order to do this we import a `gql` file only containing a fragment definition from a javascript file, and pass that along to `writeFragment({ fragment })`/`readFragment({ fragment })`.

Trying this with `graphql-mini-transforms` unfortunately throws the following error:
```js
ERROR in ./src/.../OptimisticCommentFragment.gql
Module build failed (from ./node_modules/graphql-mini-transforms/webpack.js):
GraphQLError: Syntax Error: Unexpected <EOF>
    at syntaxError (/Users/.../node_modules/graphql/error/syntaxError.js:15:10)
    at Parser.unexpected (/Users/.../node_modules/graphql/language/parser.js:1463:41)
    at Parser.parseDefinition (/Users/.../node_modules/graphql/language/parser.js:157:16)
    at Parser.many (/Users/.../node_modules/graphql/language/parser.js:1518:26)
    at Parser.parseDocument (/Users/.../node_modules/graphql/language/parser.js:111:25)
    at Object.parse (/Users/.../node_modules/graphql/language/parser.js:36:17)
    at Object.cleanDocument (/Users/.../node_modules/graphql-mini-transforms/lib/document.js:15:42)
    at Object.<anonymous> (/Users/.../node_modules/graphql-mini-transforms/lib/webpack.js:23:68)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/.../node_modules/graphql-mini-transforms/lib/webpack.js:4:58)
```
Any idea what's causing this? Or do fragments currently only work inside of other `gql` files, with the `#import` syntax?

**Comment by kaelig** [comment]
Closing this as it's been open for a while with no activity.

Feel free to reopen and add context if this should still be considered. Thank you!
