### ISSUE TITLE
Crashes when Prefetch refers to bundles that aren't loadable

### ISSUE THREAD

**Issue by zeachco** [Shopify/quilt#1805]
Request for https://github.com/Shopify/quilt/tree/main/packages/react-async

How to reproduce:
- load a web stack with a focus flag
- trigger a pre-fetcher that is not focused

```trace
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `ConnectedPrefetcher`.

    at createFiberFromTypeAndProps (https://web-cdn.myshopify.io/webpack/assets/dll/vendor.js:291219:21)
    at createFiberFromElement (https://web-cdn.myshopify.io/webpack/assets/dll/vendor.js:291242:15)
    at reconcileSingleElement (https://web-cdn.myshopify.io/webpack/assets/dll/vendor.js:281487:23)
    at reconcileChildFibers (https://web-cdn.myshopify.io/webpack/assets/dll/vendor.js:281547:35)
    at reconcileChildren (https://web-cdn.myshopify.io/webpack/assets/dll/vendor.js:284016:28)
    at updateHostComponent (https://web-cdn.myshopify.io/webpack/assets/dll/vendor.js:284556:3)
    at beginWork (https://web-cdn.myshopify.io/webpack/assets/dll/vendor.js:285881:14)
    at HTMLUnknownElement.callCallback (https://web-cdn.myshopify.io/webpack/assets/dll/vendor.js:267442:14)
    at HTMLUnknownElement.__trace__ (https://web-cdn.myshopify.io/webpack/assets/dll/vendor.js:4702:28)
    at Object.invokeGuardedCallbackDev (https://web-cdn.myshopify.io/webpack/assets/dll/vendor.js:267491:16)
```

Proposition: the addition of a kill switch with React's `useDidCatch` and disabling the failing bundle

pros
- allow dev build with focus flag not to crash all the time
- reduce the amount of concurrent requests made if the bundle is unload-able

con
- if fails upon a network reset, it wont retry to preload and just load on demand

**Comment by zeachco** [comment]
> Thanks @zeachco! The idea of adding a kill switch(dev mode only? due to presence of focus flag) seems awesome.

Aiming for _dev mode_ only, unless we want to kill switch after X amount of fails and just set dev to `1` and prod to higher but that's is probably a premature optimization
