### ISSUE TITLE
`TypeError: topic.toUpperCase is not a function` when using receiveWebhook

### ISSUE THREAD

**Issue by donaldgray** [Shopify/quilt#633]
## Overview
I'm trying to use the `receiveWebhooks` middleware to receive requests. I'm getting the call okay but then getting the following error when the request comes in:

```
  TypeError: topic.toUpperCase is not a function
      at D:\Repos\shopify-app\node_modules\@shopify\koa-shopify-webhooks\dist\receive.js:26:46
      at step (D:\Repos\shopify-app\node_modules\tslib\tslib.js:133:27)
      at Object.next (D:\Repos\shopify-app\node_modules\tslib\tslib.js:114:57)
      at D:\Repos\shopify-app\node_modules\tslib\tslib.js:107:75
      at new Promise (<anonymous>)
      at Object.__awaiter (D:\Repos\shopify-app\node_modules\tslib\tslib.js:103:16)
      at receiveWebhookMiddleware (D:\Repos\shopify-app\node_modules\@shopify\koa-shopify-webhooks\dist\receive.js:14:24)
      at dispatch (D:\Repos\shopify-app\node_modules\koa-compose\index.js:42:32)
      at bodyParser (D:\Repos\shopify-app\node_modules\koa-bodyparser\index.js:86:11)
      at process.internalTickCallback (internal/process/next_tick.js:77:7)
```

Attaching the debugger I can see that topic is a pending promise with no value when `.toUpperCase()` is called on it.

I'm setting up the router using code similar to that in the repo and using koa version 
...

## Consuming repo

> What repo were you working in when this issue occurred?
...
My own repo.

### Scope

- Is this issue related to a specific package?

koa-shopify-webhooks

---

## Checklist

- [ ] Please delete the labels section before submitting your issue
- [ ] I have described this issue in a way that is actionable (if possible)

**Comment by ismail-syed** [comment]
Hey, sorry for the delay. If this is still an issue, can you please provide us with a small reproducible test case. Thanks!

**Comment by KacherInfra** [comment]
Hi, I'm having same problem, could you share to me how you can solve this? @donaldgray
